<?php

namespace Database\Seeders;
use App\Models\Musica;
use Illuminate\Database\Seeder;

class MusicasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $musicas = [
            [
                'id' => 3,
                'nome' => 'Halftime',
                'path' => 'Nas_Halftime.mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 1,
                'id_album' => 2,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'nome' => 'It Aint Hard to Tell',
                'path' => 'Nas_It_Aint_Hard_to_Tell.mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 1,
                'id_album' => 2,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'nome' => 'Lifes a Bitch',
                'path' => 'Nas_Lifes_A_Bitch.mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 1,
                'id_album' => 2,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'nome' => 'Memory Lane',
                'path' => 'Nas_Memory_Lane.mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 1,
                'id_album' => 2,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'nome' => 'NY State Of Mind',
                'path' => 'Nas_NYState_Of_Mind.mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 1,
                'id_album' => 2,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'nome' => 'All Mine',
                'path' => 'All Mine.mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 2,
                'id_album' => 1,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'nome' => 'Heartless',
                'path' => 'Heartless.mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 2,
                'id_album' => 1,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'nome' => 'Gold Digger',
                'path' => 'Kanye West - Gold Digger ft. Jamie Foxx.mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 2,
                'id_album' => 1,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'nome' => 'Tá Demais',
                'path' => 'MARIA LEAL - TA DEMAIS (VIDEOCLIP OFICIAL).mp3',
                'Likes'=> 1,
                'duracao' => '3.10',
                'id_artista' => 3,
                'id_album' => 3,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'nome' => 'Hoje aqui só para ti',
                'path' => 'Maria Leal hoje aqui só para ti - Você na TV.mp3',
                'Likes'=> 1,
                'duracao' => '3.10',
                'id_artista' => 3,
                'id_album' => 3,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'nome' => 'A Saudade de Ti',
                'path' => 'Tony Carreira - A Saudade de Ti.mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 4,
                'id_album' => 4,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'nome' => 'Depois de ti mais nada',
                'path' => 'Tony Carreira - Depois de ti mais nada (Official Video).mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 4,
                'id_album' => 4,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'nome' => 'A Minha Casinha',
                'path' => 'A Minha Casinha.mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 5,
                'id_album' => 5,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'nome' => 'O Homem Do Leme',
                'path' => 'O Homem Do Leme.mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 5,
                'id_album' => 5,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'nome' => 'Às vezes',
                'path' => 'Xutos  Pontapés - Às vezes.mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 5,
                'id_album' => 5,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'nome' => 'Lose Yourself',
                'path' => 'Eminem - Lose Yourself [HD].mp3',
                'Likes'=> 500000,
                'duracao' => '3.10',
                'id_artista' => 6,
                'id_album' => 6,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'nome' => 'The Real Slim Shady',
                'path' => 'Eminem - The Real Slim Shady (Edited).mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 6,
                'id_album' => 6,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'nome' => 'Without Me',
                'path' => 'Eminem - Without Me.mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 6,
                'id_album' => 6,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'nome' => 'Sonhos de menino',
                'path' => 'Tony Carreira - Sonhos de menino.mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 4,
                'id_album' => 4,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'nome' => 'California Love',
                'path' => '2Pac - California Love feat. Dr. Dre.mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 7,
                'id_album' => 7,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'nome' => 'Changes',
                'path' => '2Pac - Changes ft. Talent.mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 7,
                'id_album' => 7,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'nome' => 'Hit Em Up',
                'path' => '2Pac - Hit Em Up.mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 7,
                'id_album' => 7,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'nome' => 'Ready To Die',
                'path' => '06. Ready To Die.mp3',
                'Likes'=> 500000,
                'duracao' => '4.20',
                'id_artista' => 8,
                'id_album' => 8,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'nome' => 'Who Shot Ya',
                'path' => '18. Who Shot Ya.mp3',
                'Likes'=> 500000,
                'duracao' => '3.10',
                'id_artista' => 8,
                'id_album' => 8,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'nome' => 'Gimme The Loot',
                'path' => '03. Gimme The Loot.mp3',
                'Likes'=> 500000,
                'duracao' => '3.10',
                'id_artista' => 8,
                'id_album' => 8,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'nome' => 'Suicidal Thoughts',
                'path' => '17. Suicidal Thoughts.mp3',
                'Likes'=> 3333,
                'duracao' => '3.10',
                'id_artista' => 8,
                'id_album' => 8,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'nome' => 'Protect Ya Neck',
                'path' => 'Protect Ya Neck.mp3',
                'Likes'=> 33332,
                'duracao' => '4.20',
                'id_artista' => 9,
                'id_album' => 9,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'nome' => 'ShameOnANigga',
                'path' => 'ShameOnANigga.mp3',
                'Likes'=> 89,
                'duracao' => '4.20',
                'id_artista' => 9,
                'id_album' => 9,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'nome' => 'Wu-Tang 7th Chamber',
                'path' => 'Wu-Tang 7th Chamber.mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 9,
                'id_album' => 9,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'nome' => 'Wu-Tang 7th Chamber - Part II',
                'path' => 'Wu-Tang 7th Chamber - Part II.mp3',
                'Likes'=> 89,
                'duracao' => '3.10',
                'id_artista' => 9,
                'id_album' => 9,
                'id_genero' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]

        ];
        Musica::insert($musicas);
    }
}
